amcl:
  ros__parameters:
    use_sim_time: false
    # other AMCL parameters

bt_navigator:
  ros__parameters:
    use_sim_time: false
    # other BT Navigator parameters

controller_server:
  ros__parameters:
    use_sim_time: false
    # other Controller Server parameters

planner_server:
  ros__parameters:
    use_sim_time: false
    # other Planner Server parameters

# Include other necessary configurations as per your robot setup
